//The users/customers
export  const LOGIN_REQUEST = "LOGIN_REQUEST"
export  const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export  const LOGIN_FAIL = "LOGIN_FAIL"

export  const REGISTER_REQUEST = "REGISTER_REQUEST"
export  const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export  const REGISTER_FAIL = "REGISTER_FAIL"

export  const REFRESH_TOKEN = "REFRESH_TOKEN"
export  const REFRESH_FAIL = "REFRESH_FAIL"

export  const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS"
export  const ACTIVATION_FAIL = "ACTIVATION_FAIL"

export  const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export  const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL"

export  const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS"
export  const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"

export  const PASSWORD_RESET_SUCCESS = "PASSWORD_SUCCESS"
export  const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL"

export  const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS"
export  const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL"

export  const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS"
export  const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL"

export  const FACEBOOK_AUTH_SUCCESS = "FACEBOOK_AUTH_SUCCESS"
export  const FACEBOOK_AUTH_FAIL = "FACEBOOK_AUTH_FAIL"

export  const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export  const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export  const LOGOUT_FAIL = "LOGOUT_FAIL"

//The cart
export  const CART_ADD_ITEM = "CART_ADD_ITEM"
export  const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export  const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"
export  const CART_PAYMENT = "CART_PAYMENT"
export  const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPIN_GADDRESS"

//The order
export  const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export  const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export  const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export  const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export  const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export  const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export  const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export  const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export  const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export  const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export  const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export  const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export  const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export  const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"

export  const ORDER_MINE_REQUEST = "ORDER_MINE_REQUEST"
export  const ORDER_MINE_SUCCESS = "ORDER_MINE_SUCCESS"
export  const ORDER_MINE_FAIL = "ORDER_MINE_FAIL"
export  const ORDER_MINE_RESET = "ORDER_MINE_RESET"

export  const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST"
export  const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS"
export  const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL"
export  const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET"


