//The users/customers
export  const LOGIN_REQUEST = "LOGIN_REQUEST"
export  const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export  const LOGIN_FAIL = "LOGIN_FAIL"

export  const REGISTER_REQUEST = "REGISTER_REQUEST"
export  const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export  const REGISTER_FAIL = "REGISTER_FAIL"

export  const REFRESH_TOKEN = "REFRESH_TOKEN"
export  const REFRESH_FAIL = "REFRESH_FAIL"

export  const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS"
export  const ACTIVATION_FAIL = "ACTIVATION_FAIL"

export  const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export  const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL"

export  const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export  const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export  const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS"
export  const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"

export  const PASSWORD_RESET_SUCCESS = "PASSWORD_SUCCESS"
export  const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL"

export  const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS"
export  const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL"

export  const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS"
export  const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL"

export  const FACEBOOK_AUTH_SUCCESS = "FACEBOOK_AUTH_SUCCESS"
export  const FACEBOOK_AUTH_FAIL = "FACEBOOK_AUTH_FAIL"

export  const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export  const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export  const LOGOUT_FAIL = "LOGOUT_FAIL"

export  const USER_PROFILE = "USER_PROFILE"

//The cart
export  const CART_ADD_REQUEST = "CART_ADD_REQUEST"
export  const CART_ADD_ITEM = "CART_ADD_ITEM"
export  const CART_ADD_FAIL = "CART_ADD_FAIL"

export  const CART_GET_ITEMS = "CART_GET_ITEMS"
export  const CART_UPDATE_ITEM = "CART_UPDATE_ITEM"
export  const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export  const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"
export  const CART_PAYMENT = "CART_PAYMENT"

//Shipping adderss
export  const ADDRESS_ADD_REQUEST = "ADDRESS_ADD_REQUEST"
export  const ADDRESS_SUCCESS = "ADDRESS_SUCCESS"
export  const ADDRESS_FAIL = "ADDRESS_FAIL"

export  const ADDRESS_GET_REQUEST = "ADDRESS_GET_REQUEST"
export  const ADDRESS_GET_SUCCESS = "ADDRESS_GET_SUCCESS"
export  const ADDRESS_GET_FAIL = "ADDRESS_GET_FAIL"

//The wishlist
export  const WISHLIST_ADD_REQUEST = "WISHLIST_ADD_REQUEST"
export  const WISHLIST_ADD_ITEM = "WISHLIST_ADD_ITEM"
export  const WISHLIST_GET_ITEMS = "WISHLIST_GET_ITEMS"
export  const WISHLIST_UPDATE_ITEM = "WISHLIST_UPDATE_ITEM"
export  const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM"
export  const WISHLIST_CLEAR_ITEMS = "WISHLIST_CLEAR_ITEMS"
//The order
export  const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export  const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export  const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export  const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export  const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export  const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export  const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export  const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export  const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export  const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"

export  const ORDER_MY_REQUEST = "ORDER_MY_REQUEST"
export  const ORDER_MY_SUCCESS = "ORDER_MY_SUCCESS"
export  const ORDER_MY_FAIL = "ORDER_MY_FAIL"

export  const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST"
export  const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS"
export  const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL"

export  const ORDER_ITEM_ADD_SUCCESS = "ORDER_ITEM_ADD_SUCCESS"
export  const ORDER_ITEM_ADD_FAIL = "ORDER_ITEM_ADD_FAIL"

export  const ORDER_ITEM_SUCCESS = "ORDER_ITEM_SUCCESS"

export  const REVIEW_REQUEST = "REVIEW_REQUEST"
export  const REVIEW_SUCCESS = "REVIEW_SUCCESS"
export  const REVIEW_FAIL = "REVIEW_FAIL"

export  const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST"
export  const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export  const GET_REVIEW_FAIL = "GET_REVIEW_FAIL"
//The products
export  const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export  const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export  const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL"

export  const GET_ONE_PRODUCT_REQUEST = "GET_ONE_PRODUCT_REQUEST"
export  const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS"
export  const GET_ONE_PRODUCT_FAIL = "GET_ONE_PRODUCT_FAIL"

export  const GET_BY_VARIANT_REQUEST = "GET_BY_VARIANT_REQUEST"
export  const GET_BY_VARIANT_SUCCESS = "GET_BY_VARIANT_SUCCESS"
export  const GET_BY_VARIANT_FAIL = "GET_BY_VARIANT_FAIL"

export  const GET_IMAGES_REQUEST = "GET_IMAGES_REQUEST"
export  const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS"
export  const GET_IMAGES_FAIL = "GET_IMAGES_FAIL"

export  const GET_SUBCATES_REQUEST = "GET_SUBCATES_REQUEST"
export  const GET_SUBCATES_SUCCESS = "GET_SUBCATES_SUCCESS"
export  const GET_SUBCATES_FAIL = "GET_SUBCATES_FAIL"


export  const GET_BY_CATNAME_REQUEST = "GET_BY_CATNAME_REQUEST"
export  const GET_BY_CATNAME_SUCCESS = "GET_BY_CATNAME_SUCCESS"
export  const GET_BY_CATNAME_FAIL = "GET_BY_CATNAME_FAIL"

export  const GET_BY_PAGES_REQUEST = "GET_BY_PAGES_REQUEST"
export  const GET_BY_PAGES_SUCCESS = "GET_BY_PAGES_SUCCESS"
export  const GET_BY_PAGES_FAIL = "GET_BY_PAGES_FAIL"

export  const GET_COLORS_REQUEST = "GET_COLORS_REQUEST"
export  const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS"
export  const GET_COLORS_FAIL = "GET_COLORS_FAIL"

export  const GET_SIZES_REQUEST = "GET_SIZES_REQUEST"
export  const GET_SIZES_SUCCESS = "GET_SIZES_SUCCESS"
export  const GET_SIZES_FAIL = "GET_SIZES_FAIL"

export  const GET_TAGS_REQUEST = "GET_TAGS_REQUEST"
export  const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS"
export  const GET_TAGS_FAIL = "GET_TAGS_FAIL"

export  const GET_NEWPRODUCTS_REQUEST = "GET_NEWPRODUCTS_REQUEST"
export  const GET_NEWPRODUCTS_SUCCESS = "GET_NEWPRODUCTS_SUCCESS"
export  const GET_NEWPRODUCTS_FAIL = "GET_NEWPRODUCTS_FAIL"

export  const GET_ONSALE_REQUEST = "GET_ONSALE_REQUEST"
export  const GET_ONSALE_SUCCESS = "GET_ONSALE_SUCCESS"
export  const GET_ONSALE_FAIL = "GET_ONSALE_FAIL"

export  const GET_SLIDERS_REQUEST = "GET_SLIDERS_REQUEST"
export  const GET_SLIDERS_SUCCESS = "GET_SLIDERS_SUCCESS"
export  const GET_SLIDERS_FAIL = "GET_SLIDERS_FAIL"
